### ISSUE TITLE
ports sorting

### ISSUE THREAD

**Issue by Shayen** [jchanvfx/NodeGraphQt#102]
I'm having an issue about ports position which is not stable and change every time I create.
I found that objects are stored in dictionary format before adding to nodes by loops.
I think it might be better if there were sort before adding.

![image](https://user-images.githubusercontent.com/27872000/57199313-acc00e00-6fa7-11e9-97be-009c49225915.png)

**Comment by jchanvfx** [comment]
Hi @Shayen 

Are you running python 2.x? because in python 3.6+ dictionaries are ordered by default. 

Cheers,
Johnny

**Comment by Shayen** [comment]
Hi @jchanvfx 

Yes, I'm using python 2. 
I'm moving to python 3 to solve this.

Thank you :)

**Comment by jchanvfx** [comment]
All Good 😺
