### ISSUE TITLE
zoom under mouse using alt + MMB + drag

### ISSUE THREAD

**Issue by bpjobin** [jchanvfx/NodeGraphQt#109]
Hi there! 

I've been trying to implement this in a similar project I have going on. Have you been able, by any chance, to make the zoom (using alt + MMB + drag) follow the cursor's initial click position? I mean exactly like in Nuke.

**Comment by jchanvfx** [comment]
Hi @bpjobin 

Currently this is not implemented but is on the list 😺

**Comment by jchanvfx** [comment]
Looks like this is already implemented

https://github.com/jchanvfx/NodeGraphQt/blob/534bb9cac1765d57f7b0456ef56e76b4aa6f87ba/NodeGraphQt/widgets/viewer.py#L411-L414

https://github.com/jchanvfx/NodeGraphQt/blob/534bb9cac1765d57f7b0456ef56e76b4aa6f87ba/NodeGraphQt/widgets/viewer.py#L135-L162
