### ISSUE TITLE
Examples!

### ISSUE THREAD

**Issue by jaxxtrend** [jchanvfx/NodeGraphQt#110]
No have example explained basic operations inside a node, for example addition, substraction, etc.
And no execution examples: runtime and deffered .
Add please.

**Comment by jchanvfx** [comment]
Hi @jaxxtrend 

This node graph framework is very much a work in progress, it's a hobby project that I work on and off in my spare time as for execution examples I haven't got to that point yet but will keep you updated. 😺  

Cheers,
Johnny

**Comment by mikeporetti** [comment]
thanks for all you do Johnny, its an excellent work in progress.

**Comment by jchanvfx** [comment]
Updated docs with examples section:
https://jchanvfx.github.io/NodeGraphQt/api/html/index.html

not much examples up at them moment but will continue to add more in future.
