### ISSUE TITLE
Setup NodeGraphQt from Git for project via requirements.txt

### ISSUE THREAD

**Issue by jaxxtrend** [jchanvfx/NodeGraphQt#111]
in virtual environment i make requirements.txt file:
"""
PySide2==5.12.3
Qt.py==1.2.0
QtPy==1.7.1
shiboken2==5.12.3
https://github.com/jchanvfx/NodeGraphQt/archive/master.zip
"""
When run 'pip install -r requirements.txt' i got error message:
ModuleNotFoundError: No module named 'Qt'

Result, no any module installed.

**Comment by jaxxtrend** [comment]
The work fix looks like this:
 setup.py
...
setuptools.setup (
     name = 'NodeGraphQt',
     version = version,
     version = '0.0.5', 
...

Not sure if this is a good practice.

**Comment by jaxxtrend** [comment]
I made commit 6ed875e26f7643133c0e93e6034656485a47caa1
And i remove python version checking from a requirements.txt

**Comment by jchanvfx** [comment]
Hey @jaxxtrend 

All good 😄 will look into it.

Thanks,
Johnny
