### ISSUE TITLE
Cutter tool proposal

### ISSUE THREAD

**Issue by Daelex** [jchanvfx/NodeGraphQt#113]
Hey Johnny.

Really great project you've got here. We're using it to prototype rigging tool, and it's really easy to use, modify and understand it's mechanics.
I don't have experience using QGraphic library, the way you draw node, connexions, etc ... it seems very powerfull.

So I was wondering how we could make a cutter tool to cut connexions between ports. Like in maya node editor.
Basically, this would be something like this.
- hit an hotkey (alt-shit for instance)
- drag your cursor on the grid
- draw a cut line between first click and cursor pos
- detect intersecting connexions lines
- break connexions in data.

Thanks,
Alex

**Comment by jchanvfx** [comment]
Hey @Daelex 

I've just implemented a slicer tool where you can use the shortcut ``Alt+Shift+LMB+Drag``

Cheers,
Johnny

![slicer](https://user-images.githubusercontent.com/7546915/59757145-38cf9000-92df-11e9-8014-3802b3b9ef88.png)
