### ISSUE TITLE
Port snapping or indication feature

### ISSUE THREAD

**Issue by Nevolutionize** [jchanvfx/NodeGraphQt#115]
Currently the ports feel too small when attempting to connect while zoomed out and the connection attempt ends up missing the port.

I believe release 0.0.2 introduced port highlighting; this works fine when the cursor is hovering over, but fails while in an event. Like when you click+drag onto a port to create a pipe.

It would be great if there was a way to do either of the following:
- Snap the pipe to the port when within a falloff range. 
- Add a falloff range around a port so that it recognizes a cursor is nearby
- Allow port highlighting to work within events, so there's some indication that a connection will be made
- Allow us to set the port size

**Comment by Nevolutionize** [comment]
Just tested out 0.0.7 and it works great.
Thanks for all your hard work on this project!

**Comment by jchanvfx** [comment]
Awesome thanks 😸
