### ISSUE TITLE
Error when installing NodeGraphQt with pip (Python error)

### ISSUE THREAD

**Issue by Luk3M** [jchanvfx/NodeGraphQt#120]
This might be related to #111 .
When using `pip install https://github.com/jchanvfx/NodeGraphQt/archive/master.zip`, the following error occurs:

```
ERROR: Could not find a version that satisfies the requirement python>=3.6 (from NodeGraphQt==0.0.9) (from versions: none)
ERROR: No matching distribution found for python>=3.6 (from NodeGraphQt==0.0.9)
```
I'm currently using Python 3.7
Installing the version 0.0.4 and earlier of NodeGraphQt gives no errors, so this might been introduced on 0.0.5

**Comment by jchanvfx** [comment]
updated `setup.py` in release `0.0.10` thanks to @jaxxtrend
