### ISSUE TITLE
Request for port_disconnected event

### ISSUE THREAD

**Issue by Nevolutionize** [jchanvfx/NodeGraphQt#122]
It would be nice to have a **port_disconnected** signal on the NodeGraph object.
Currently, there's only a **port_connected** signal being emitted by the **Port.connect_to()** function.

**Comment by jchanvfx** [comment]
Hi @Nevolutionize 

I've released v0.0.11 with the **port_disconnected** signal. 😸 
https://github.com/jchanvfx/NodeGraphQt/releases/tag/v0.0.11

Cheers,
Johnny

**Comment by Nevolutionize** [comment]
Thanks so much Johnny.
