### ISSUE TITLE
Node UUID

### ISSUE THREAD

**Issue by Nevolutionize** [jchanvfx/NodeGraphQt#128]
What are your thoughts on generating UUID's for nodes?

I'm using NodeGraphQt in a way where the **NodeGraph** is constantly switching between graph definitions using the **load_session** method.

The graph has a layer with a model that contains relationships between the node objects and a custom parameter editor.

The issue with node.id is that it's different each time a new node is created (save/load etc.).
I know the node name is unique, so I could use that; however, I feel like having a **node.uuid** property would be far more optimal long term solution.

This UUID can be generated once on initial node creation and then saved or reapplied to the node when serializing/de-serializing the graph.

**Comment by jchanvfx** [comment]
Hi @Nevolutionize 

The `node.id` is different each time a node is deserialised or created, this is to prevent having nodes with the same id when using actions like copy/paste, duplicate or loading nodes multiple times in one session. 

The node name is unique as well but I feel thats not really a safe way to go.

Would it work if you created a custom node property `uuid`?

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import uuid
from NodeGraphQt import BaseNode, NodeGraph, QtWidgets, setup_context_menu


class MyNode(BaseNode):

    # set the initial default node name.
    NODE_NAME = 'my node'

    def __init__(self):
        super(MyNode, self).__init__()

        # create a custom UUID property.
        self.create_property('UUID', str(uuid.uuid4()))

        # create connection ports.
        self.add_input('foo')
        self.add_output('bar')

if __name__ == '__main__':
    app = QtWidgets.QApplication([])

    graph = NodeGraph()
    graph.register_node(MyNode)
    graph.widget.resize(1100, 800)
    graph.widget.show()

    setup_context_menu(graph)

    # create a couple nodes.
    node_a = graph.create_node('nodeGraphQt.nodes.MyNode',
                               name='node foo',
                               pos=[0, 0])
    node_b = graph.create_node('nodeGraphQt.nodes.MyNode',
                               name='node bar',
                               pos=[350, 0])

    print('node foo: ' + node_a.get_property('UUID'))
    print('node bar: ' + node_b.get_property('UUID'))

    app.exec_()
```

**Comment by Nevolutionize** [comment]
Sorry for the late reply.

I felt that the unique node name wasn't a safe bet either, so I ended up creating a UUID in the subclass of my node as well.

Thanks!

**Comment by jchanvfx** [comment]
Sweet as 😺
