### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by xslendix** [jchanvfx/NodeGraphQt#129]
Widgets:
- Number widget
- Button widget

Node behaviour:
- If 2 nodes don't have the same color for input and output, they cannot connect.
- The color of the node connection changes based upon the node input and output color. When selected, the color is inverted or set to another color.

General changes:
- Runnable nodes. With this, nodes can be ran easily. Bassicly an interpreter.

**Comment by ArnoChenFx** [comment]
You can run 'example_auto_nodes.py'. AutoNode can make ports have different data type appera different color. Different port type cannot connect.

**Comment by jchanvfx** [comment]
``v0.1.2`` you can now embed your own custom widget in a node object see example.
https://jchanvfx.github.io/NodeGraphQt/api/html/examples/ex_node.html#embedding-custom-widgets
