### ISSUE TITLE
set pipe style issue

### ISSUE THREAD

**Issue by ArnoChenFx** [jchanvfx/NodeGraphQt#140]
In graph.py  line 548
Now the code is "style = style if 0 >= style >= pipe_max else PIPE_LAYOUT_CURVED".
The correct is "style = style if 0 <= style <= pipe_max else PIPE_LAYOUT_CURVED".

**Comment by jchanvfx** [comment]
You are right 😺 thanks for catching that bug I've made an update to the master branch.

Cheers,
Johnny

https://github.com/jchanvfx/NodeGraphQt/commit/8973c9d808e3826ad8adbc99c18af0c802291a02
