### ISSUE TITLE
Syntax error in setup.py

### ISSUE THREAD

**Issue by jjennings955** [jchanvfx/NodeGraphQt#148]
https://github.com/jchanvfx/NodeGraphQt/blob/master/setup.py#L21

    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jason\AppData\Local\Temp\pip-req-build-vzec4h4j\setup.py", line 21
        'Documentation' :: 'https://jchanvfx.github.io/NodeGraphQt/api/html/index.html',
                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Note: the line following it makes the same mistake
https://github.com/jchanvfx/NodeGraphQt/blob/master/setup.py#L21

**Comment by jchanvfx** [comment]
Hey @jjennings955 ,

Thanks for catching that I've made an update to the master branch. 😺 
https://github.com/jchanvfx/NodeGraphQt/commit/2e6b76056a5b5f518a6e47ecaffab211ffd40381

Cheers,
Johnny
