### ISSUE TITLE
Signal for node_selection_changed

### ISSUE THREAD

**Issue by PaulSchweizer** [jchanvfx/NodeGraphQt#159]
First off, thanks for this amazing library!

I am currently exploring it, so I might be overlooking things, but I can't seem to find a proper `node_selection_changed(selected, deselected)` signal that gets called every time the selection changes. 

Basically I am imagining the same behavior as in `QAbstractItemView`:

https://srinikom.github.io/pyside-docs/PySide/QtGui/QAbstractItemView.html?highlight=selectionchanged#PySide.QtGui.PySide.QtGui.QAbstractItemView.selectionChanged

I found this previous ticket #69 but it only emits a signal when a node is selected, not when the selection **changes**.

**Comment by jchanvfx** [comment]
Hey @PaulSchweizer ,

Thanks for checking out the frame work, I've added a `node_selection_changed` signal to the `master` branch.

Cheers,
Johnny
