### ISSUE TITLE
the shape of port

### ISSUE THREAD

**Issue by ChuKuang** [jchanvfx/NodeGraphQt#160]
Whether to support the modification of the shape of port, such as a triangle

**Comment by jchanvfx** [comment]
Hi @ChuKuang ,

An update has been made  to the `master` branch you should now be able to now override a ports painter function see example link below 😸 

https://jchanvfx.github.io/NodeGraphQt/api/html/examples/ex_port.html#example-triangle-port

Cheers,
Johnny

**Comment by ChuKuang** [comment]
I have modified your code and made port picture support

**Comment by jchanvfx** [comment]
Awesome thanks for checking out the framework 😃
