### ISSUE TITLE
ImportError: cannot import name 'SubGraph' from 'NodeGraphQt.base.node'

### ISSUE THREAD

**Issue by mrunion** [jchanvfx/NodeGraphQt#170]
Line 829 of NodeGraphQt > base > **utils.py** has the following line:

`from .node import BaseNode, SubGraph`

and it should probably be changed to the following, since SubGraph appears to have moved to the **graph.py** file:

```
from .node import BaseNode
from .graph import SubGraph
```

More info:
I am running on MacOS 10.15.4 using Python 3.7 in a virtual environment.

**Comment by mrunion** [comment]
I just found the PR #169 addresses this issue, so my Issue can be ignored if PR #169 is pulled in.

**Comment by jchanvfx** [comment]
I've just merged PR #169 into `master` branch 😸
