### ISSUE TITLE
 The node name is displayed in the wrong position

### ISSUE THREAD

**Issue by ChuKuang** [jchanvfx/NodeGraphQt#171]
the latest，   the node name not displayed on the previous, but displayed next to it
![微信截图_20200518205846](https://user-images.githubusercontent.com/20549836/82215776-7a7f1580-994a-11ea-9a43-e6a6fc615ce7.png)

**Comment by ArnoChenFx** [comment]
It's not wrong, we move title next to the node in vertal mode to avoid title collider with pipe
