### ISSUE TITLE
Node Port Connection Issue

### ISSUE THREAD

**Issue by Everzen** [jchanvfx/NodeGraphQt#173]
This is a very silly issue to do with port connection, that I have tried to strip back and demo with a minimum example. I talk through this in a 2 minute video that you can grab from here:

https://boltonuni-my.sharepoint.com/:v:/g/personal/rpj1_bolton_ac_uk/EYIp3LUVG2NJqPzbWu9SlecByyriebRkwLHgFbvNhl1Oew?e=TPx9vP

It would be amazing to know what you think. You may well think it is very silly and not worth looking at, but I thought I would share in case it is of interest!  

Thank you so much for the amazing library! It is so so cool to work with! 

All the best,

Rich

**Comment by jchanvfx** [comment]
Hi @Everzen,

Thanks for the detailed video and catching this bug 😸  I'll take a look into this issue when I get a chance.

Cheers,
Johnny

**Comment by Everzen** [comment]
Awesome! Thanks for all the amazing work!

**Comment by jchanvfx** [comment]
NodeGraphQt v0.1.1 released. 😃

**Comment by Everzen** [comment]
Great stuff Johnny!

Thanks for sharing! I will definitely look to move to this as soon
as possible.

Thanks again for all the amazing work!

All the best,

Rich
