### ISSUE TITLE
Click and drag does not work at node's left-most and right-most region

### ISSUE THREAD

**Issue by yamiyukiharu** [jchanvfx/NodeGraphQt#176]
Hi, I realized that click and drag does not work in the areas highlighted below:
![image](https://user-images.githubusercontent.com/12526810/96816382-f2002600-144f-11eb-8f9f-c1697769e63c.png)

I looked at the source code and found the issue:
node_base.py: (line 199 to 206)
```python
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            start = PortItem().boundingRect().width() - PORT_FALLOFF
            end = self.boundingRect().width() - start
            x_pos = event.pos().x()
            if not start <= x_pos <= end: 
                event.ignore()
        super(NodeItem, self).mousePressEvent(event)
```
I have no idea what condition is it checking, but when i commented out this section to let it process the event normally, everything works fine.

**Comment by jchanvfx** [comment]
Thanks for finding that bug I've just made some updates to the `master` branch 😺
