### ISSUE TITLE
Group Node

### ISSUE THREAD

**Issue by xxvfx** [jchanvfx/NodeGraphQt#179]
like katana, group and liveGroup
group node can group select nodes, 
liveGroup node can import nodes from a json file，if json has been modified， the liveGroup node can automatic updates,
and if edit liveGroup node's attribute, this edit can be save

**Comment by ArnoChenFx** [comment]
In NodeGraphQt,  SubGraph node is Group node.

https://jchanvfx.github.io/NodeGraphQt/api/html/graph.html#subgraph

https://user-images.githubusercontent.com/24894259/78112502-e5bf6780-7430-11ea-8149-f25fc958edf3.gif
https://user-images.githubusercontent.com/24894259/78230978-b37f3a00-7504-11ea-806a-9086e9277b9d.gif

https://github.com/jchanvfx/NodeGraphQt/blob/master/example_auto_nodes/networks/example_SubGraph.json

**Comment by xxvfx** [comment]
I didn't read it very carefully,  I'm sorry。
This is great, thank you very much!!!
