### ISSUE TITLE
Compatibility python3.6

### ISSUE THREAD

**Issue by VincentDB** [jchanvfx/NodeGraphQt#186]
Hello, i'm actually using this project in a python3.6 environment and it's working well. Well done. But in the setup.py, it's specified `python_requires='>=3.7'` so i can't build a package in my virtualenv.

**Comment by jchanvfx** [comment]
Hey @VincentDB ,

Thanks for checking out the framework I've just updated the ``setup.py`` in the ``master`` branch 😃 

Cheers,
Johnny
