### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'cook'

### ISSUE THREAD

**Issue by terxy** [jchanvfx/NodeGraphQt#191]
![image](https://user-images.githubusercontent.com/54308805/110974916-c5e63280-8367-11eb-876a-f1819ac798f0.png)
Hello!
I want to create a subgraph in node A from graph, but when I update the all nodes (update_nodes(graph.root_node().children()))
and I have the following error:
 _File "C:\Python27\lib\site-packages\NodeGraphQt\example_auto_nodes\node_base\utils.py", line 23, in update_nodes
    _update_nodes(topological_sort_by_down(all_nodes=nodes))
  File "C:\Python27\lib\site-packages\NodeGraphQt\example_auto_nodes\node_base\utils.py", line 11, in _update_nodes
    node.cook()
AttributeError: 'Node' object has no attribute 'cook'_

Can you please help me?

**Comment by jchanvfx** [comment]
Hi @terxy,

Sorry a bit late on the reply 😄 but as of version `0.2.0` a new `NodeGraphQt.GroupNode` and `NodeGraphQt.SubGraph` class has been added to framework.

https://jchanvfx.github.io/NodeGraphQt/api/html/nodes/GroupNode.html
https://jchanvfx.github.io/NodeGraphQt/api/html/graph.html#NodeGraphQt.SubGraph

Cheers,
Johnny
