### ISSUE TITLE
Error with passing "painter_func" input to the BaseNode "add_input" method. 

### ISSUE THREAD

**Issue by Everzen** [jchanvfx/NodeGraphQt#193]
Hi guys,

Firstly, thank you so much for such an awesome library. The functionality is just amazing and is helping me no end with putting my ideas into practice. I have recently got around to upgrading my NodegraphQt to version 0.1.3. It has gone really smoothly, but there is one issue which I cannot get to work properly, and it is passing a "painter_func" to the BaseNode add_input method. 

I have boiled the problem down to the most simple form I can using the demo code on your fantastic help documentation. I have attached a short zipped python file to demo the problem. When this runs there is an argument error (with my current setup) when ever you try and pass the "draw_square_port" function (from the help), to the "painter_func" input. I did not get this error in the previous version of NodegraphQt. 

The code will error on line 52 and 65 since both try to pass this function.

I apologise if I am doing something silly and wrong, but I thought I would raise it in case it is a bug. If it is something to do with my setup, then I will happily press on with trying to figure it out. I am on python 3.7.3.

Thanks for all your time and energy with this project, it is an amazing library to have!  

All the best,

Rich 

[painter_funct_Error.zip](https://github.com/jchanvfx/NodeGraphQt/files/6175917/painter_funct_Error.zip)

**Comment by jchanvfx** [comment]
Hi @Everzen ,

Looks like modules ``QtGui`` and ``QtCore`` is missing from your import line at the very top.

Cheers,
Johnny

**Comment by Everzen** [comment]
Thanks for the reply! I will look into it. I am really sorry if it is such a silly oversight! Too much coding when tired! Thanks for the help!

**Comment by jchanvfx** [comment]
All good bro 😺
