### ISSUE TITLE
Widget size=0 error

### ISSUE THREAD

**Issue by Mougrouff** [jchanvfx/NodeGraphQt#195]
When a NodeViewer widget is used, resizing it fast may lead to collapse and division by zero error.

We fixed it when overloading function by adding this check :

```
if 0 in [self.size().width(), self.size().height()]:
    self.resize(self._last_size)
super(CustomNodeViewer, self).resizeEvent(event)
```

**Comment by jchanvfx** [comment]
Nice Thanks @Mougrouff 😺 I've just updated the master branch.
