### ISSUE TITLE
`BaseNode.set_property` does not update contents of text input

### ISSUE THREAD

**Issue by tamasmuncsan** [jchanvfx/NodeGraphQt#203]
I have a class which extends `BaseNode`. I add text inputs to this node with `BaseNode.add_text_input`.

When I call `BaseNode.set_property` I expect the text inputs content to be updated, however this does not happen.

It worked with `v0.1.1` but after the latest releases it does not work anymore.

Am I missing something here, or is this a bug?

**Comment by mara004** [comment]
I have the same problem - set_property seems to take no effect.
