### ISSUE TITLE
Unexpected pipe disconnections/reassignments

### ISSUE THREAD

**Issue by hectormauer** [jchanvfx/NodeGraphQt#205]
I'm using `NodeGraphQt` `0.1.3` and have two issue:
The first one is that when moving a selected node on top of another node, it selects one of the pipes and reassigns it to the top port of the first selected node:
![issue_1](https://user-images.githubusercontent.com/24248439/115571388-d8cd1a80-a2b6-11eb-8ac7-64920e08bbed.gif)

I think it boils down to here: https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/base/graph.py#L161

The second issue, when a node is already on top of another, if you click to select it and right in that position there is a port from the below node, it tries to create a connection from there as well:
![issue_2](https://user-images.githubusercontent.com/24248439/115571640-18940200-a2b7-11eb-81fe-fbc092990881.gif)

I believe this comes from here: https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/widgets/viewer.py#L622

Thanks and congratulatios for the great work!

**Comment by jchanvfx** [comment]
Hi @hectormauer,

Thanks for checking out the node graph framework. The first issue it is the expected behaviour if a node intersects a pipe then the a new node connection is established. As for the second issue I've just made an fix to the ``master`` branch thanks for catching that bug 😺 

Cheers,
Johnny

**Comment by hectormauer** [comment]
Hi @jchanvfx,

Thank you for addressing this so quickly. I appreciate the first issue is the expected behaviour, I just fear sometimes one may remove/modify pipes without really willing to do so. I found it happened to me when just trying to shuffle/reorder my nodes.

Thanks again for your work 👍 

Cheers,
Hector

**Comment by jchanvfx** [comment]
All good bro will look into implementing a function to disable pipe collisions. #206

**Comment by hectormauer** [comment]
haha thanks mate :)
I guess we could close this issue now
