### ISSUE TITLE
Dragging Nodes over pipes auto connecting

### ISSUE THREAD

**Issue by ironWolf1990** [jchanvfx/NodeGraphQt#211]
Thank you for the awesome work you did with the program! I just wanted to know how to disable the feature where the nodes auto connects to the pipe it is dragged over.

**Comment by jchanvfx** [comment]
Hi @ironWolf1990 , this feature is not yet implemented here the related ticket https://github.com/jchanvfx/NodeGraphQt/issues/206 😺
