### ISSUE TITLE
Boxes doesn't elongate enough when using many connectors

### ISSUE THREAD

**Issue by Simon-BVs** [jchanvfx/NodeGraphQt#221]
When adding a connector to boxes, the box do not elongate enough from a tiny bit.
The problem is hard to see with usual number of connectors but can be seen when having over 30 connectors.
As you can see on the screenshot under in the lower right part, the last connector is displayed outside the box :

![Image1](https://user-images.githubusercontent.com/87752560/126452734-31fbb568-eb88-44fc-bc59-3b6365ff85a9.png)

I think creating a box with over 50 connectors should allow you to see the display bug.
Let me know what you think !

**Comment by jchanvfx** [comment]
fixed in v0.2.0 release.
