### ISSUE TITLE
SubGraph: Usage Example Please

### ISSUE THREAD

**Issue by jlgerber** [jchanvfx/NodeGraphQt#227]
It is not clear from the documentation  how the subgraph is to be used. The docs say that SubGraph is the baseclass for all subgraph nodes, but it seems to lack the methods to add inputs and outputs... not to mention handling diving into a subgraph.

How is subgraph intended to be used?

Update:

I have found an example but it also demonstrates auto nodes. Perhaps it would be useful to have a non-cooking example as well as some info in the documentation?

**Comment by jchanvfx** [comment]
`v0.2.0` I've refactored how sub graphs work, you now have a `GroupNode` class that'll contain a `SubGraph` if it expanded.
https://chantastic.nz/NodeGraphQt/api/html/nodes/GroupNode.html
https://chantastic.nz/NodeGraphQt/api/html/graph.html#NodeGraphQt.SubGraph
