### ISSUE TITLE
Zigbee network

### ISSUE THREAD

**Issue by martin9115** [jchanvfx/NodeGraphQt#229]
Hi, can we use this for Zigbee network ?

**Comment by mara004** [comment]
Please elaborate a bit what `Zigbee network` is and how we can help you with the consideration whether to use NodeGraphQt or not.

**Comment by martin9115** [comment]
I use Xbee/Zigbee modules and i wish to establish mesh network topology.

I work on this project  and i'm trying to develop better GUI for the network topology, so i was wondering if NodeGraphQt can support Zigbee mesh network ?
https://github.com/zzeitt/ZigBee-GUI

I'm new to NodeGraphQt, so i'm not familiar with capabilities of NodeGraphQt, and i'm sorry if my qestion sound stupid.

**Comment by mara004** [comment]
NodeGraphQt is an abstract framework for creating node-graph based GUIs with PySide2 or PyQt5.
It does not provide support for specific tasks on its own, but it offers a framework that can be used to build applications for custom purposes.

There is [API documentation](https://jchanvfx.github.io/NodeGraphQt/api/html/index.html) with usage examples. You can also take a look at [example_math_nodes.py](https://github.com/jchanvfx/NodeGraphQt/blob/master/example_math_nodes.py) and [example_auto_nodes.py](https://github.com/jchanvfx/NodeGraphQt/blob/master/example_auto_nodes.py) to evaluate whether NodeGraphQt is suitable for your use case.

**Comment by martin9115** [comment]
Yes, i know that.
In the project i send you link for the GUI is done by PyQT5.

So, i was wondering is there example of GUI made by NodeGraphQt built for Zigbee network ?

**Comment by mara004** [comment]
> So, i was wondering is there example of GUI made by NodeGraphQt built for Zigbee network ?

As far as I know, there isn't -- the examples in the documentation are mostly for learning and demo purposes. They are not related to such a very specifc (and probably complex) task.

**Comment by mara004** [comment]
If you think your question is answered, please close the issue.
