### ISSUE TITLE
Subgraphs do not work

### ISSUE THREAD

**Issue by Martmists-GH** [jchanvfx/NodeGraphQt#246]
```py
class CompoundNode(BaseNode, SubGraph):
    NODE_NAME = "Compound"
    
    def is_editable(self):  # Needed because it crashes otherwise
        return True
```

It is not possible to enter the subgraph when a node type like this is added, despite the "Jump In" and "Jump Out" options appearing in the context menu (which, for reference, also do not work).

**Comment by Martmists-GH** [comment]
After editing the example from auto nodes, it seems to work. However, both the auto nodes example and mine have an issue where copying a subgraph node (not even pasting) causes it to not carry over attributes properly, and in some cases even lose its attachment points.

**Comment by Martmists-GH** [comment]
The issue seems to be related to _serialize, where update_model is called. It seems to serialize the value from the widget rather than the property itself which may have been changed from the code, which in turn is setting the number of inputs/outputs to zero.

Removing the code to use the widget properties sets the values in the widgets to zero however, while keeping the correct number of inputs/outputs. Not sure how this should be fixed.

**Comment by jchanvfx** [comment]
As of ``v0.2.0`` the code base has been refactored with a new [GroupNode](https://jchanvfx.github.io/NodeGraphQt/api/html/nodes/GroupNode.html) class and a new [SubGraph](https://jchanvfx.github.io/NodeGraphQt/api/html/graph.html#subgraph) class.
