### ISSUE TITLE
config file for menus and hotkeys

### ISSUE THREAD

**Issue by ef-ex** [jchanvfx/NodeGraphQt#254]
Hi

It would be really great if the menus and hotkeys would read the data from a simple config file like a yaml or json for example.
I always find it kinda complicated when i need to alter py files for this and then pull an update for example.

all the best

Hannes

**Comment by jchanvfx** [comment]
new release with implemented ``NodeGraph.set_context_menu_from_file()``:
https://github.com/jchanvfx/NodeGraphQt/releases/tag/v0.4.0

docs:
https://chantastic.nz/NodeGraphQt/api/html/graph.html#NodeGraphQt.NodeGraph.set_context_menu_from_file
example config:
https://github.com/jchanvfx/NodeGraphQt/blob/master/examples/hotkeys/hotkeys.json
