### ISSUE TITLE
Publish NodeGraphQt in the Python Package Index

### ISSUE THREAD

**Issue by LucasCTN** [jchanvfx/NodeGraphQt#265]
This library can be available through `pip install NodeGraphQt` by publishing in https://pypi.org.
There's a tutorial [here](https://packaging.python.org/en/latest/tutorials/packaging-projects/) about how to do it. I believe this would require the maintainer to publish it after all metadata is added.

You can also do it automatically through Github Actions by following [this tutorial](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/).

**Comment by Mougrouff** [comment]
Up : It would be very helpful for our project, could you upload every tag version ?

**Comment by laurapons** [comment]
+1

**Comment by vytnav** [comment]
+1

**Comment by translunar** [comment]
+1

**Comment by jchanvfx** [comment]
I've put something up https://pypi.org/project/NodeGraphQt/ just need to figure out how to set it up with Github actions. 😺
