### ISSUE TITLE
subcontrol-position key error

### ISSUE THREAD

**Issue by Mougrouff** [jchanvfx/NodeGraphQt#270]
In [NodeGraphQt//widgets/node_widgets.py](https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/widgets/node_widgets.py) the following code is causing an issue because key 'subcontrol-position' is not initialized in every situations. Especially if align == 'left'.

```
if align == 'center':
    style_dict['QGroupBox::title']['subcontrol-position'] = 'top center'
elif align == 'left':
    style_dict['QGroupBox::title']['subcontrol-position'] += 'top left'
    style_dict['QGroupBox::title']['margin-left'] = '4px'
elif align == 'right':
    style_dict['QGroupBox::title']['subcontrol-position'] += 'top right'
    style_dict['QGroupBox::title']['margin-right'] = '4px'
```

**Comment by Soooya** [comment]
I tried to add` 'subcontrol-position':'' ` in  `style_dict['QGroupBox::title']` , then there was no no more error message.

**Comment by samyhocine** [comment]
Hi :)

This has been fixed and merged ;)

Refer to this PR : https://github.com/jchanvfx/NodeGraphQt/pull/267
