### ISSUE TITLE
Setting NODE_LAYOUT_DIRECTION per node graph.

### ISSUE THREAD

**Issue by LucaScheller** [jchanvfx/NodeGraphQt#272]
Hey,  
quick question about the vertical node graph node display style:
It seems like currently one can only set it globally by changing the NODE_LAYOUT_DIRECTION variable in the constants.py.
Are there plans to make this configurable per graph? (Are there reasons that it can't be configured per graph? If not, I could look into making a PR for this if you want.)

Thank you so much for creating this UI framework, it is very straight forward and easy to use!
Cheers,
Luca

**Comment by LucaScheller** [comment]
Created a PR here: #273

**Comment by jchanvfx** [comment]
Released v0.3.0 with a `set_layout_direction()` function

https://chantastic.nz/NodeGraphQt/api/html/graph.html#NodeGraphQt.NodeGraph.set_layout_direction
https://chantastic.nz/NodeGraphQt/api/html/nodes/NodeObject.html#NodeGraphQt.NodeObject.set_layout_direction

**Comment by LucaScheller** [comment]
Amazing :) Thank you very much!
