### ISSUE TITLE
Can you provide a c++ version? and Can you recommend other open source projects with c++ versions?

### ISSUE THREAD

**Issue by isteelcx** [jchanvfx/NodeGraphQt#283]
Do you know about this project? https://github.com/paceholder/nodeeditor.git

**Comment by isteelcx** [comment]
Your project has basically met the goals of [paceholder/nodeeditor.git](https://github.com/paceholder/nodeeditor.git), so if you can show the c++ version of the project, it will be very welcome

**Comment by jchanvfx** [comment]
Hi @isteelcx, I'm not much of a C++ guy so I can't help you there sorry. 😭

**Comment by isteelcx** [comment]
> Hi @isteelcx, I'm not much of a C++ guy so I can't help you there sorry. 😭 

Oh！This is a great pity！

**Comment by jchanvfx** [comment]
wow
