### ISSUE TITLE
Restrict connection of pins

### ISSUE THREAD

**Issue by ughstudios** [jchanvfx/NodeGraphQt#285]
Is there a way to add constraints so that only certain pins can connect to others? For example, triangles with taingles, squares with squares, and circles with circles? Also, can we restrict which pins can connect to which other nodes?

**Comment by jchanvfx** [comment]
`v0.6.0` released with new pipe connection constraints on a port.
https://jchanvfx.github.io/NodeGraphQt/api/html/examples/ex_port.html#connection-constrains
