### ISSUE TITLE
How to make the shape of a node into a circle

### ISSUE THREAD

**Issue by q13926117923** [jchanvfx/NodeGraphQt#287]
~

**Comment by jchanvfx** [comment]
Hi @q13926117923,

I've not yet implement this feature as this is related to issue #12 but, it is possible by reimplementing the `NodeItem._paint_vertical`, `NodeItem. _paint_horizontal` class functions.

have a look at the group node implementation.
https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/qgraphics/node_group.py#L20
https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/nodes/group_node.py#L26

**Comment by jchanvfx** [comment]
I've just added a new experimental `NodeGraphQt.BaseNodeCircle` class.

https://jchanvfx.github.io/NodeGraphQt/api/html/nodes/BaseNode.html#basenode-circle
