### ISSUE TITLE
get_value method on Node Widgets is replaced by the value itself

### ISSUE THREAD

**Issue by aloytag** [jchanvfx/NodeGraphQt#288]
When using `add_combo_menu()` or `add_text_input()` in order to add a built-in widget, I get the following error message:

```
File "/home/user/.local/lib/python3.9/site-packages/NodeGraphQt/widgets/node_widgets.py", line 116, in on_value_changed
    self.value_changed.emit(self.get_name(), self.get_value())
TypeError: 'str' object is not callable
```

If I use `add_checkbox()`, I get a similar result:

```
File "/home/user/.local/lib/python3.9/site-packages/NodeGraphQt/widgets/node_widgets.py", line 116, in on_value_changed
    self.value_changed.emit(self.get_name(), self.get_value())
TypeError: 'bool' object is not callable
```

It seems that, at some point, the **`get_value`** method is replaced by the value itself. It can be reproduced using **`basic_example.py`**.

**NodeGraphQt version:** 0.5.0
**Qt.py version:** 1.3.7
**PySide2 version:** 5.15.2.1
**Python version:** 3.9.2
**OS:** Debian GNU/Linux 11 (bullseye)

Regards.

**Comment by aloytag** [comment]
For debugging purposes, I modified the **line 116** on **node_widgets.py** like this:

```
if isinstance(self.get_value, str):
    print("GET_VALUE IS THIS STRING:", self.get_value)
else:
    print("GET_VALUE IS NOT A STRING")
self.value_changed.emit(self.get_name(), self.get_value())
```

Then, I used this example graph with a single node, adding de the `add_text_input()` method for a "Level" property (Python compressed file): [test_error.zip](https://github.com/jchanvfx/NodeGraphQt/files/10308353/test_error.zip)

Next, I executed the script with this result (see the strange look): 

![1_After_execution](https://user-images.githubusercontent.com/36411739/209672107-b35bded0-0e5b-4d8c-8cdc-b58cd3642b77.png)

Then, I changed the value on the text input widget and pressed ENTER (changed 10 to 105). In the terminal I get:

```
GET_VALUE IS NOT A STRING
Level 105
```

... with no errors. So, it's working as expected. The second line is just the return of a function connected to the `value_changed` signal. And the look changed a little like this:

![2_After_changing_the_value](https://user-images.githubusercontent.com/36411739/209673303-96dc6df5-f16b-420e-a419-eb0f29510096.png)

But then I changed the value again and pressed ENTER, and I get:

```
GET_VALUE IS THIS STRING: 105
Traceback (most recent call last):
  File "/home/usuario/.local/lib/python3.9/site-packages/NodeGraphQt/widgets/node_widgets.py", line 120, in on_value_changed
    self.value_changed.emit(self.get_name(), self.get_value())
TypeError: 'str' object is not callable
```

Then, I can confirm that the **get_value** method is replaced by the widget value itself, but the old one, not the new value. And If I continue changing the value after this point, I always get the old value in **get_value**.

**Comment by aloytag** [comment]
I've found the error. Line 1027 in **node_base.py** says:

`self._widgets[name].get_value = value`

Instead, it must say:

`self._widgets[name].set_value(value)`

And for the initial strange look of the node on the first image, I had to run the `update()` method manually. Is that normal?

**Comment by jchanvfx** [comment]
Awesome thanks for catching that bug 😺
