### ISSUE TITLE
how to add auto_complete within node text input ?

### ISSUE THREAD

**Issue by RichardTrouve** [jchanvfx/NodeGraphQt#295]
hi, not an issue per say, I hope the question is self explenatory enough, i'm trying to figure out how to implement an autocompletion feature into nodes text input. is it actually possible ?

**Comment by jchanvfx** [comment]
Hi @RichardTrouve,

I think it might be possible you could try accessing the `QLineEdit` widget from the node and then set autocomplete on it.

```python
from NodeGraphQt import NodeGraph, BaseNode


class TestNode(BaseNode):

    __identifier__ = 'my.test'
    NODE_NAME = 'My Text Node'

    def __init__(self):
        super(TestNode, self).__init__()
        self.add_input('in')
        self.add_output('out')

        self.add_text_input('text_input')

        node_widget = node.get_widget('text_input')
        line_edit_widget = node_widget.get_custom_widget()

        print(line_edit_widget)
```

or you could set your own custom widget to the node from this example.
https://jchanvfx.github.io/NodeGraphQt/api/html/examples/ex_node.html#embedding-custom-widgets

Cheers,
Johnny
