### ISSUE TITLE
from Qt import QtWidgets

### ISSUE THREAD

**Issue by lukasc-ubc** [jchanvfx/NodeGraphQt#299]
Hello,

I am trying to get started with NodeGraphQt, and the first problem I run into is 
`from Qt import QtWidgets`
gives the error:
`ModuleNotFoundError: No module named 'Qt'`

The Qt import line appears at the top of every file.

I have installed PySide2, which allows for:
`from PySide2 import QtCore, QtWidgets`

I have also installed PyQt, which allows for:
`from PyQt5.QtWidgets import QApplication, QLabel`

Is there something I am missing to have your code work?  Perhaps a search and replace of Qt to PySide2 or PyQt5?

Perhaps you could add a brief documentation in your getting started section on how to install the tool. 

Thank you very much,
Lukas

**Comment by jchanvfx** [comment]
Hi @lukasc-ubc , 

Looks like you need to install the `Qt.py` shim module here https://github.com/mottosso/Qt.py

Cheers,
Johnny
