### ISSUE TITLE
Pipe and node visibility inconsistency

### ISSUE THREAD

**Issue by itscassie** [jchanvfx/NodeGraphQt#310]
When I set the visibility of a child node to false (i.e., by using the command 'set_property("visible", False)'), the pipe connected to the input port remains visible. 
I assume that the pipe connected to that node should also become invisible at this stage. 
It would be appreciated if the visibility of the connected pipe could be changed accordingly.

**Comment by jchanvfx** [comment]
Hi @itscassie,

Looks like the node visibility is not fully implemented and currently there's no way to make pipe objects a hidden connection through the node graph at this stage.

For now the only way to do something similar is you can hide the node with the pipes disconnected. 

Here's a function that'll do that and will also register to the undo stack.

```python
def hide_node(node):
    """
    hide node and disconnect the connections.
    
    Args:
        node (NodeGraphQt.BaseNode): node object.
    """
    node.graph.beginMacro('hide node "{}"'.format(node.name()))
    for port in node.input_ports():
        for connected_port in port.connected_ports():
            port.disconnect_from(connected_port)
    for port in node.output_ports():
        for connected_port in port.connected_ports():
            port.disconnect_from(connected_port)
    node.set_property('visible', False)
    node.graph.endMacro()
```

Thanks for pointing that out will have to implement some logic to support hidden pipes. 😃 

Cheers,
Johnny

**Comment by jchanvfx** [comment]
closing this issue just made a new release: https://github.com/jchanvfx/NodeGraphQt/releases/tag/v0.5.3
