### ISSUE TITLE
Update and values transmission

### ISSUE THREAD

**Issue by Zelfior** [jchanvfx/NodeGraphQt#318]
Hi,

It is more a question than a bug. about how we can actually use it. 

Can we access to data from nodes that are linked to the current node? For example if we want to make a sum or multiply node.

How are nodes updated, is the model_update function called everytime there is a change in a tree? does it propagate to the nodes present in the tree? To go back to the multiply example, it would let update the value if we change one of the summed values.

Thanks

**Comment by jchanvfx** [comment]
Hi @Zelfior 

Currently `NodeGraphQt` is more of a UI framework that can be customized, any of the business logic you'll need to implement on top of it.

Here's a link to a basic setup for a node graph.
https://jchanvfx.github.io/NodeGraphQt/api/html/examples/ex_overview.html#getting-started

The node graph also has a `NodeGraph.property_changed` signal.
https://jchanvfx.github.io/NodeGraphQt/api/html/graph.html#NodeGraphQt.NodeGraph.property_changed

Here's a snippet to get values from a connected node:

```python
 from Qt import QtWidgets

from NodeGraphQt import NodeGraph, BaseNode


class TestNode(BaseNode):

    __identifier__ = 'my.test'
    NODE_NAME = 'My Text Node'

    def __init__(self):
        super(TestNode, self).__init__()
        self.add_input('in')
        self.add_output('out')
        self.add_text_input('baz', text='hello')
        self.create_property('foo', 'bacon')
        self.create_property('bar', 'eggs')


if __name__ == '__main__':
    app = QtWidgets.QApplication([])

    graph = NodeGraph()
    graph.register_node(TestNode)
    graph.show()

    node_A = graph.create_node('my.test.TestNode')
    node_B = graph.create_node('my.test.TestNode')

    # connect the 2 nodes.
    node_B.set_input(0, node_A.output(1))

    # get the name of node_A from the connected input of node_B
    print(node_B.input(0).connected_ports()[0].node().name())

    # get the value of node_A "baz" property from the connected input of node_B
    print(node_B.input(0).connected_ports()[0].node().get_property('baz'))

    app.exec_()
```

**Comment by Zelfior** [comment]
@jchanvfx 
Thanks for your answer :D

I managed to make the value transmission and children updates when a value is changed now.

I would like to get to draw an image within a node, ideally put a matplotlib inside a node. It is possible to do with QWidgets through FigureCanvasQTAgg from matplotlib.backends.backend_qt5agg. Have you ever tried doing so within your framework? I tried a couple of things, a node is created at what seems to be the right size, but nothing is shown within the node.

(You can find in my depo a gross copy of yours that i changed for debug purpose, i'm not planning to claim your code)

Thanks
Zelfior

**Comment by jchanvfx** [comment]
Cool all good @Zelfior if you’re wanting to embed an image into a node you could do by setting an image on a QLabel widget and then adding that into the node.

Here’s an example on embedded a custom widget.

https://jchanvfx.github.io/NodeGraphQt/api/html/examples/ex_node.html#embedding-custom-widgets

**Comment by Zelfior** [comment]
Thanks for the link, i managed to make it work :)

![Capture du 2023-04-07 09-52-44](https://user-images.githubusercontent.com/87946970/230576390-9a36eed7-52b1-4b71-b527-2a314d3e71aa.png)

**Comment by jchanvfx** [comment]
Nice!

**Comment by EssenOH** [comment]
Wondering how the plot is placed on the right size within the node if you the custom widget utilized QLabel.
Seems, the size of plot widget should occupy the region at beginning of the node initialization.... any idea ?
