### ISSUE TITLE
Issue related to undo move backdrop nodes

### ISSUE THREAD

**Issue by itscassie** [jchanvfx/NodeGraphQt#320]
When using backdrop nodes
Under the scenario that I got several other nodes wrapped in a backdrop node,
when I move all the nodes wrap in backdrop node, and then undo the "move nodes" action (using the context menu)

sometimes I was unable to move all the node back to the original position,
the backdrop node itself move back, but the nodes it wrapped remains at the same position

The frequency of encountering this bug is around 1/2, not sure what cause this happens.

**Comment by itscassie** [comment]
Found the use cases that cause different result:
1) click and hold the LMB to select the backdrop node then drag (without release the LMB):
only backdrop node will be undo
2) click on LMB to select the backdrop node, **release LMB**, click LMB again and drag:
all nodes wrap in backdrop node will be undo

More specifically, the scenario differs on the "select" signal, when moving nodes
1) If some nodes was auto selected by selecting the backdrop node then move => unable to undo/redo
2) If all node was selected before moving => able to undo/redo

There are two circumstances that mousePressEvent will be triggered: 
a) NodeViewer
b) BackdropNodeItem


a) when mousePressEvent is triggered in NodeViewer:
it will update it's _node_positions property
and is updated by finding selected nodes and records their view and current xy pos
b) when mousePressEvent is triggered in NodeMoveCmd:
it will find _node_positions and see that nodes are records in it.


What happens when selecting wrapped nodes by clicking a backdrop node:
the select event is in mousePressEvent of BackdropNodeItem, and the wrapped selected nodes was not counted in selected_nodes()  of NodeViewer.

**Comment by jchanvfx** [comment]
Hi @itscassie, 
I've just made a new release `v0.5.8` with some tweaks to the backdrop selection logic.
https://github.com/jchanvfx/NodeGraphQt/releases/tag/v0.5.8
