### ISSUE TITLE
Black text on dark background

### ISSUE THREAD

**Issue by Zelfior** [jchanvfx/NodeGraphQt#322]
Hi!

The text (labeling the widgets) appears black in my case and not gray like in the doc:
![image](https://user-images.githubusercontent.com/87946970/232231221-e443a6cc-463e-4971-b5ff-e01465c10ec0.png)

It makes it barely readable. I would like to change it to a lighter color, i saw that it goes to some palette palette somewhere, but i didn't really get where it comes from. The color set to the node text only applies to the ports as you can see here (the white text is in a custom widget qLabel, so it was easy to change):
![image](https://user-images.githubusercontent.com/87946970/232231415-d1d944d2-c2d5-4369-bab4-4ffaf0e5ceab.png)

Can you lead me to what i should change?

Thanks,
Zelfior

**Comment by jchanvfx** [comment]
Hi @Zelfior,

This should already be fixed in the latest release `v0.5.5`

Cheers,
Johnny

**Comment by jchanvfx** [comment]
https://github.com/jchanvfx/NodeGraphQt/pull/306

**Comment by Zelfior** [comment]
Indeed it was, thank you :)
