### ISSUE TITLE
copy paste and slice tool

### ISSUE THREAD

**Issue by Zelfior** [jchanvfx/NodeGraphQt#332]
Hi,

The alt+shift tool doesn't work anymore once we did ctrl+V (ctrl+C doesn't break the slice tool).

I have a few questions about the way the node layout is being build, to not make an issue for every not bug related question i have, do you mind contacting me at the adress: zelfior@gmail.com? (i will remove this sentence once you answered it)

Thanks
Zelfior

**Comment by jchanvfx** [comment]
Hi @Zelfior,

looks like there was a typo in the `NodeGraph.pipe_slicing` function return causing the serializing to disable pipe slicer thanks for catching that bug 😃.

as for questions on the frame work it might be better to post as a separate issue for now.

Cheers,
Johnny
