### ISSUE TITLE
Access to the node layout/grid

### ISSUE THREAD

**Issue by Zelfior** [jchanvfx/NodeGraphQt#335]
Hi,

I am making coupling between node inputs and widgets, the purpose would be to make the widget disappear and be replaced by a label showing the value when plugged. It is displayed in the figure below:
![image](https://user-images.githubusercontent.com/87946970/236574402-8088d879-8921-498e-ae76-fb40e319a18b.png)

We can see that the grid used in the layout leaves room for the hidden widget, i would like to get rid of it, but i couldn't get a hand on it through the classes inheritance. Where can we find it?

I also witnessed some mis-updating in the nodes size (didn't get what triggered it yet), but it seems to be only getting bigger but not smaller sometimes. I guess calling a setSizeConstraint on the right layout would solve my issue, so i would like to get access to it.

It would be quite hand to get several column for the options of my node displaying the matplotlib graph, does that match with the way your nodes manage their widgets? i expect changing the grid from my side would make the trick.

Thanks in advance,
Zelfior

PS: you can go play around in my repo see if there are features you want to add to your module

**Comment by jchanvfx** [comment]
Hi @Zelfior,

There's a couple new functions implemented on the `BaseNode` object for showing and hiding widgets.
http://chantonic.com/NodeGraphQt/api/nodes/BaseNode.html#NodeGraphQt.BaseNode.hide_widget
http://chantonic.com/NodeGraphQt/api/nodes/BaseNode.html#NodeGraphQt.BaseNode.show_widget
is this what you're after?

**Comment by Zelfior** [comment]
Hi!
Yes great, it solves the first issue i talked about (the one illustrated on the pictures) :)

Now if i want to have two columns in the grid layout, do you want another bug for this specific question?

Zelfior

**Comment by jchanvfx** [comment]
Cool thanks @Zelfior , yeah that would be great I'm not too sure what you mean with the columns in the grid layout?
