### ISSUE TITLE
Context menu commands functionalities

### ISSUE THREAD

**Issue by snorthman** [jchanvfx/NodeGraphQt#351]
The context menu could be much more powerful with some simple additions. Currently, and correct me if I'm wrong, there is no signal for when the context menu is opened (other than catching a right-click manually).

If we would have such a signal, I could loop over all added commands with add_command, and hide/disable/reveal/enable any relevant commands given the context. You could possibly do away with the existing node-specific override functionality, because using the requested signal allows us to check what node(s) are selected and go from there.

This implies the existence of `NodeGraph.get_commands(): List` and `NodeGraphCommand.hide(bool)`, `NodeGraphCommand.enable(bool)`. 

Should this be included as a feature, ensuring a disabled item is greyed out would be neat. 

`context_menu.get_command('mycommand').qaction.setDisabled(True)` actually does work, but does not change the style of the command.

**Comment by jchanvfx** [comment]
Hi @snorthman,

I've just made a new release `v0.6.5` with a new `context_menu_prompt` signal.
http://chantonic.com/NodeGraphQt/api/graph.html#NodeGraphQt.NodeGraph.context_menu_prompt

as for the enabling and disabling of the command I'll will look into the styling of it later on.

thanks for the suggestions 😃.

Cheers,
J

**Comment by snorthman** [comment]
I notice you have written it as `NodeGraphCommand.set_enabled(bool)`, but for hiding it is `NodeGraphCommand.hide()` and `NodeGraphCommand.show()`. I think a `NodeGraphCommand.set_hidden(bool)` is better.

Example:

```python
has_selected_nodes: bool = len(self.selected_nodes()) > 0
self.command_cut.set_enabled(has_selected_nodes)
self.command_copy.set_enabled(has_selected_nodes)
self.command_delete.set_enabled(has_selected_nodes)
```

**Comment by jchanvfx** [comment]
will put that into the next release.
