### ISSUE TITLE
NodeGraph.save_session cannot serialize sets

### ISSUE THREAD

**Issue by snorthman** [jchanvfx/NodeGraphQt#356]
`NodeGraph.save_session(str)` does not work, as it cannot serialize `set` objects.

Here is where a set occurs in my serialized session:

```python
unserializable: set = serialized['graph']['accept_connection_types']['simulator.SimulatorNode']['in']['sim']['simulator.SimulationNode']['out']
```

Two easy solutions, rather than avoid sets in serialization:

[stackoverflow SetEncoder](https://stackoverflow.com/questions/8230315/how-to-json-serialize-sets)

or

```python
def serialize_json(obj):
  if isinstance(obj, set):
    return list(obj)
  return obj

json.dumps(text, default=self.serialize_json)
```

**Comment by jchanvfx** [comment]
addressed in `v0.6.10` thanks for catching that bug 😺
