### ISSUE TITLE
context_menu_prompt and NodeViewer.pos()

### ISSUE THREAD

**Issue by snorthman** [jchanvfx/NodeGraphQt#357]
I am not sure what the correct method is to retrieve the current mouse position. When I want to create a node under the current mouse position, using

`graph.viewer().pos()` always gets me (0, 0). `graph.viewer()._previous_pos` gets me the correct position, but its a hidden variable. Is `NodeViewer.pos()` not working as intended?

Is there a totally different way of doing this, that I am not aware of?

**Comment by jchanvfx** [comment]
Hi @snorthman, 

This is probably an oversight of mine, you're right it would be the `_previous_pos` attr I just haven't exposed it in the NodeGraph class.

Cheers,
J

**Comment by jchanvfx** [comment]
actually no the `_previous_pos` is not mapped to the scene.

**Comment by jchanvfx** [comment]
I've just made a new release and added a new `NodeGraph.cursor_pos()` func.

http://chantonic.com/NodeGraphQt/api/graph.html#NodeGraphQt.NodeGraph.cursor_pos
