### ISSUE TITLE
Signals are not emitted during "undo".

### ISSUE THREAD

**Issue by roma-p** [jchanvfx/NodeGraphQt#373]
Hello, I have a question regarding the signals and the undo stack:

When "Undo" is done, and the last action done was changing the value of a node property:
- the value of the property is reset to its previous value
- the signal **NodeGraph.property_changed** is emitted, which is the behaviour I was expecting.

But! If the last action was a connection or disconnection of two nodes, then, undoing won't emit
**NodeGraph.port_connected**, **NodeGraph.port_disconnected**.

Same goes for node creation / deletion and the emission of **NodeGraph.node_created**, **NodeGraph.node_deleted** signals.

For the connection disconnection, I found out that **BaseNode.on_input_connected** and **BaseNode.on_input_disconnected**
were called, so I used those instead. But I am stuck for the creation / deletion of nodes.

Am I missing something?
Thanks in advance for your help !

**Comment by jchanvfx** [comment]
Hi @roma-p, 

Thanks for catching that a bit of a oversight but I've released a new version here 😃 
https://github.com/jchanvfx/NodeGraphQt/releases/tag/v0.6.25

Cheers,
J

**Comment by roma-p** [comment]
Thank you so much ! I will test that.
