### ISSUE TITLE
GroupNode fails to delete an input port

### ISSUE THREAD

**Issue by kaizu** [jchanvfx/NodeGraphQt#382]
Hello,

`GraphNode` fails to delete input ports.  `delete_output` seems to work properly.

In the function `delete_input`, it calls `get_output` as in `delete_output`:

https://github.com/jchanvfx/NodeGraphQt/blob/main/NodeGraphQt/nodes/group_node.py#L152

Should it be `get_input`, right?

Thank you in advance.

**Comment by jchanvfx** [comment]
Hi @kaizu, 

Looks like you've found a bug thanks for catching that 😸.

Cheers,
Johnny

**Comment by jchanvfx** [comment]
I've just released a new version.
https://github.com/jchanvfx/NodeGraphQt/releases/tag/v0.6.26

Cheers,
Johnny
