### ISSUE TITLE
Same type port connections

### ISSUE THREAD

**Issue by GTN0707** [jchanvfx/NodeGraphQt#404]
Hello,
Is it possible to have ports of the same types  (input or output) connected to each other?

**Comment by jchanvfx** [comment]
Hi @GTN0707,

In the `NodeGraph` class there's a set_acyclic() function you can set to `True`.
https://chantonic.com/NodeGraphQt/api/graphs/NodeGraph.html#NodeGraphQt.NodeGraph.set_acyclic

See also 
https://chantonic.com/NodeGraphQt/api/nodes/BaseNode.html#NodeGraphQt.BaseNode.add_accept_port_type
https://chantonic.com/NodeGraphQt/api/port.html#NodeGraphQt.Port.add_accept_port_type

Cheers,
Johnny

**Comment by GTN0707** [comment]
Thank you @jchanvfx! Your work is amazing!

**Comment by jchanvfx** [comment]
Awesome 😀

**Comment by GTN0707** [comment]
I do have a follow up question:
What if all I want to constrain is the port type but want to leave port name and node type unconstrained? 
{
    'port_name': 'foo'
    'port_type': PortTypeEnum.IN.value
    'node_type': 'io.github.jchanvfx.NodeClass'
}

**Comment by jchanvfx** [comment]
You don't have to specify a port constrain type just leave the NodeGraph with acyclic set to `True`

**Comment by GTN0707** [comment]
I assume you meant acyclic set to False right? So that we can have a cyclic graph?
If so yes I have done that. But I'm still not able to do same type port connections. E.g. IN to IN, OUT to OUT. 
I haven't been able to trace down which part of code is preventing that.

**Comment by jchanvfx** [comment]
hmm... ok I think you might have to make some tweaks to the `NodeViewer.apply_live_connection`

https://github.com/jchanvfx/NodeGraphQt/blob/main/NodeGraphQt/widgets/viewer.py#L992

but I'm not sure if it's possible to have the same port type connections as you have to rework the `PipeItem` class too. 😢 

https://github.com/jchanvfx/NodeGraphQt/blob/main/NodeGraphQt/qgraphics/pipe.py#L24

**Comment by GTN0707** [comment]
just want to drop in to report that I think I did it! yay! It was a pretty convoluted snow ball of changes... like you pointed out, apply_live_connection and pipeItem class. also everything related to PortTypeEnum logic under graph, viewer, serialize, deserialize, undo, redo, connected_ports, redraw_connected_pipes...
I don't have a programming background but diving into your library definitely motivated me to learn python! Thank you so much!

**Comment by jchanvfx** [comment]
Awesome bro keep on keeping on 👍

**Comment by MegaBanana** [comment]
> just want to drop in to report that I think I did it! yay! It was a pretty convoluted snow ball of changes... like you pointed out, apply_live_connection and pipeItem class. also everything related to PortTypeEnum logic under graph, viewer, serialize, deserialize, undo, redo, connected_ports, redraw_connected_pipes... I don't have a programming background but diving into your library definitely motivated me to learn python! Thank you so much!

Hi, any chance you publish your code ?
