### ISSUE TITLE
passing data from one node to anothre

### ISSUE THREAD

**Issue by geoffroygivry** [jchanvfx/NodeGraphQt#405]
Hi! 
Could you kindly show us how to pass data from one node to another please? I couldn't find anything in the documentation. Thank you very much!

**Comment by jchanvfx** [comment]
Hi @geoffroygivry ,

`NodeGraphQt` is a barebones node graph UI framework you'll need to implement your own logic on top of it 

I've had a similar question ask previously is this what you're after? 😺 
https://github.com/jchanvfx/NodeGraphQt/issues/86#issuecomment-444389406

Cheers,
Johnny

**Comment by geoffroygivry** [comment]
Hey Johnny, many thanks for your fast reply, for sure now it makes sense, and I will implement my logic! Thanks again for making this amazing framework, it is by far the best out there! Best of luck and say hi to the Weta peeps for me (old Weta guy here!).

**Comment by jchanvfx** [comment]
Awesome 😺

**Comment by FooDawn** [comment]
@geoffroygivry when implementing your logic and looking at example in issue #86 you don't need to implement your own connecting function, you can use already implemented function of BaseNode connected_input_nodes 

https://chantonic.com/NodeGraphQt/api/nodes/BaseNode.html#NodeGraphQt.BaseNode.connected_input_nodes

At least in my case this function really helped.

**Comment by geoffroygivry** [comment]
Thanks a lot @FooDawn, got it now!
