### ISSUE TITLE
Menubar Shortcuts in Windows OS

### ISSUE THREAD

**Issue by GTN0707** [jchanvfx/NodeGraphQt#408]
I tried to incorporate the node graph into a QMainWindow. And then replicated the menubar with associated shortcuts based on context_menu.

Everything appeared to work fine in macOS. 
However in Windows, only some specific windows native shortcuts like copy paste delete, open save.. worked. 
All other custom shortcuts didn't trigger. 

Do you happen to know why? 

I was looking through the code and found this. Is this relevant? 
[https://github.com/jchanvfx/NodeGraphQt/blob/a900a4b1256a4cf0791019f8796958dbf75f0df8/NodeGraphQt/widgets/viewer.py#L125]()

**Comment by jchanvfx** [comment]
Hi @GTN0707,

Do you have like a small example snippet I can have a look at?

**Comment by GTN0707** [comment]
Hey @jchanvfx,

Of course! I just loaded data from hotkeys.json and added to menubar in QMainWindow

`# Iterate over each item in the menu
                    for item_info in menu_items:
                        item_type = item_info.get('type')
                        if item_type == 'command':
                            item_label = item_info.get('label')
                            file_path = item_info.get('file')  # Get the file path from the JSON data
                            function_name = item_info.get('function_name')
                            shortcut = item_info.get('shortcut')
                            keys = item_info.get('keys')  # Get the custom keys from the JSON data

                            # Dynamically load the module from the file path
                            spec = importlib.util.spec_from_file_location("hotkey_functions", file_path)
                            hotkey_functions = importlib.util.module_from_spec(spec)
                            spec.loader.exec_module(hotkey_functions)

                            # Get the function object from the module
                            fn = getattr(hotkey_functions, function_name)

                            # Creating menu action
                            action_label = f"{item_label}\t{keys}"  # Align keys to the right

                            action = QtWidgets.QAction(action_label, graph)
                            action.triggered.connect(lambda _, fn=fn: fn(graph))`
                            
After wrestling with it a bit I think I figured it out. Reading thru [https://doc.qt.io/qt-6/qkeysequence.html](url), Windows is just not as shortcut friendly as other OSs. 
So instead of showing the actual shortcut combinations in hotkeys.json I just used all QKeySequence keys instead. "keys" are just for display on the menu. 
      {
        "type":"command",
        "label":"Delete",
        "file":"hotkeys/hotkey_functions.py",
        "function_name":"delete_nodes",
        "shortcut":"QtGui.QKeySequence.Delete",
        "keys": "Del"
      },
      {
        "type":"separator"
      },
      {
        "type":"command",
        "label":"Select All",
        "file":"hotkeys/hotkey_functions.py",
        "function_name":"select_all_nodes",
        "shortcut":"QtGui.QKeySequence.SelectAll",
        "keys": "Ctrl + A"
      },
