### ISSUE TITLE
is it possible to generate subgraphs in nodes?

### ISSUE THREAD

**Issue by iwayato** [jchanvfx/NodeGraphQt#409]
so i want to click on nodes to display nodes inside them, like a subgraph

**Comment by jchanvfx** [comment]
Hi @iwayato,

There's a `GroupNode` class  that can expand in a subgraph you can have a look into here.

https://chantonic.com/NodeGraphQt/api/nodes/GroupNode.html
https://chantonic.com/NodeGraphQt/api/graphs/SubGraph.html

note that the subgraph is not fully developed as it is tied to the UI see issue https://github.com/jchanvfx/NodeGraphQt/issues/376

Cheers,
Johnny

**Comment by iwayato** [comment]
thanks!

**Comment by iwayato** [comment]
Is there a possibility to do this recursively? I mean nesting one subgraph inside another indefinitely

thanks!

**Comment by jchanvfx** [comment]
Hmm... it maybe possible? I haven't tried myself but you could reimplement the `SubGraph` class so when it initialises it'll build a `GroupNode` that then is expanded.

https://github.com/jchanvfx/NodeGraphQt/blob/main/NodeGraphQt/base/graph.py#L2487
https://github.com/jchanvfx/NodeGraphQt/blob/main/NodeGraphQt/base/graph.py#L2910
