### ISSUE TITLE
How to change the node title (or bind it to another model propertie)

### ISSUE THREAD

**Issue by arshavirmirzakhani** [jchanvfx/NodeGraphQt#429]
Hello
When i create two or more nodes of same type a number will be appended to the node name at title and is there any way to fix it or bypass it by changing view?
Thanks

**Comment by arshavirmirzakhani** [comment]
Also I forgot to mention I'm using a fork of this project called OdenGraphQt for pyside6 compatibility

**Comment by jchanvfx** [comment]
Hi @arshavirmirzakhani,

You'll probably need to re-implment the `NodeGraph` class and override the `add_node` function.

https://github.com/jchanvfx/NodeGraphQt/blob/main/NodeGraphQt/base/graph.py#L1366

**Comment by arshavirmirzakhani** [comment]
thanks a lot here is a summary of what i did:

i created a new class that inherits the NodeGraph class and reimplemented add_node and create_node functions by removing get_unique_name and setting the variable to the actual node name

and it worked ,thanks !
