### ISSUE TITLE
AttributeError: 'NodeItem' object has no attribute 'all_widgets'

### ISSUE THREAD

**Issue by asadefrango** [jchanvfx/NodeGraphQt#48]
I can't get widgets from Nodes
error:
```
return self.item.all_widgets().items()
AttributeError: 'NodeItem' object has no attribute 'all_widgets'
```
The code: 
```python
def all_widgets(self):
    return self._widgets
```
is missing on class: NodeItem;  file: NodeGraphQt/widgets/node.py

**Comment by jchanvfx** [comment]
Indeed you're right @asadefrango looks like I forgot to update the methods in the `Node` object in module NodeGraphQt/interfaces/node.py thanks for catching that 😃
