### ISSUE TITLE
return inherited (plugin and extension) node classes from viewer's selected_nodes(), rather than basic nodeItem

### ISSUE THREAD

**Issue by rigGitLikeYouDigGit** [jchanvfx/NodeGraphQt#67]
Currently calling `nodeGraph.viewer().selected_nodes()` returns a list of `NodeGraphQt.widgets.node_base.NodeItem()` instances, regardless of if the selected node types have inherited further. This makes it difficult to query selected nodes in other windows if they are extensions of the base class, and makes it difficult to access any extra functionality that may have been added.

**Comment by edart76** [comment]
Hey man, turns out I'm a blind moron. Thanks very much for the tip, and for this awesome framework!

**Comment by jchanvfx** [comment]
all good man :smile_cat: I still need to write up some documentation for this node graph it's on the list.

Thanks.
