### ISSUE TITLE
Allow renaming of nodes on doubleclick

### ISSUE THREAD

**Issue by edart76** [jchanvfx/NodeGraphQt#77]
I'm using the library as part of an autorig system, and it's becoming very important that users can interact fluidly with the ui to change the displayed names of nodes - most of the interaction conventions I'm looking at implementing are very maya-like, which I get might not be the best vision for this library as a whole. However, the convention of double-clicking a displayed name to change it is common across many applications.

I can have a crack at implementing this if you're too busy - it would probably live in the node_abstract module, and involve a couple of new signals to and from the node model or vendor to check the new name is valid.

**Comment by jchanvfx** [comment]
Hi @edart76,

It's on my to do list. I'm currently working on implementing the properties bin widget where the user can load up a node and modify its attributes, it's not quite there yet but if the changing of the node name is something you need soon I have a branch that has the `node_double_clicked` signal added.

https://github.com/jchanvfx/NodeGraphQt/pull/80/files

for checking if the new node name is valid I think it's already a implementation.
https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/base/node.py#L256
https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/base/graph.py#L451

Cheers,
Johnny 😺

**Comment by jchanvfx** [comment]
Nodes can now be edited in the `PropertiesBinWidget` widget.

see example
```python
from NodeGraphQt import NodeGraph

graph = NodeGraph()

viewer = graph.viewer()
viewer.show()

# show the properties bin when a node is "double clicked" in the graph.
properties_bin = graph.properties_bin()
properties_bin.setWindowFlags(QtCore.Qt.Tool)

def show_prop_bin(node):
    if not properties_bin.isVisible():
        properties_bin.show()

graph.node_double_clicked.connect(show_prop_bin)
```
