### ISSUE TITLE
Automatic node layout 

### ISSUE THREAD

**Issue by jf---** [jchanvfx/NodeGraphQt#82]
Cool project 🍹 - for more elaborate DAG's, having a graph layout algorithm clean up the DAG might be useful

**Comment by jchanvfx** [comment]
Thanks,  That does sounds really useful but the node graph is still very much a work in progress, it'll be a while before something like that will be implemented but will keep it in mind 😺 . 

Cheers,
J

**Comment by IdrisMiles** [comment]
Having multiple de/serialisation strategies could be quite cool for this, for example a long winded method could be:
- writing out the graph with [pydot](https://pypi.org/project/pydot/) into a DOT file 
- use graphvis's dot program to do the layout for you
- re-load a graph from  the DOT source code, or just read the position attributes

The above is perhaps not that practical really, but by supporting DOT it would allow some interesting interopability with other packages like [networkx](https://networkx.github.io/) (Although this is now going beyond this issue)

**Comment by ArnoChenFx** [comment]
Currently we can use L or Ctrl+L to layout nodes.

**Comment by tamasmuncsan** [comment]
@ArnoChenFx I've read the docs and found no mention of `CTRL+L` or `L` binding for the layout function... Can you please show an example?

**Comment by jchanvfx** [comment]
https://jchanvfx.github.io/NodeGraphQt/api/html/graph.html#NodeGraphQt.NodeGraph.auto_layout_nodes
https://github.com/jchanvfx/NodeGraphQt/blob/master/NodeGraphQt/base/graph.py#L1637
