### ISSUE TITLE
Delete input/output ports

### ISSUE THREAD

**Issue by edart76** [jchanvfx/NodeGraphQt#88]
For some applications, it may be handy to change the number of inputs and outputs dynamically, but currently there is no way to delete a port once it is added to the node.

**Comment by jchanvfx** [comment]
Currently I haven't implemented any way of deleting ports as this effects some of the functions in the `NodeGraphQt.Node` class, however I've added a `set_visible()` function to `NodeGraphQt.Port` so you can show or hide ports.

hope this helps 😸 

http://chantasticvfx.com/nodeGraphQt/html/port.html#NodeGraphQt.Port.set_visible

![hide_ports](https://user-images.githubusercontent.com/7546915/50335356-e26fd780-056f-11e9-82a5-b33d423b75d8.gif)

**Comment by websterek** [comment]
Could you add this function also for widgets/property like "text_input"? It's will be very useful :)

**Comment by ArnoChenFx** [comment]
Currently we can use NodeGraphQt.BaseNode.delete_input and NodeGraphQt.BaseNode.delete_output to delete port.

We can also use NodeGraphQt.BaseNode.set_ports to reset ports.
