### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by kidintwo3** [jchanvfx/NodeGraphQt#91]
Hi!

I'm using Pyside2 v5.6.0a1 for Python 2.7 on Windows 10.

Strangely the **setup_context_menu** module does not seem to register the key commands. And functions that are not using "lambda" does not even work through the menu.

Only "Tab", "alt" etc. seem to work but those are not registered through a QAction for the menu.

**Comment by jchanvfx** [comment]
Hi @kidintwo3,

I've made some updates to the `master` branch that should address the menus and command not appearing in the in the node graph now. 😸

**Comment by kidintwo3** [comment]
Sweet! Stellar work btw.

**Comment by jchanvfx** [comment]
Thanks 😃
