### ISSUE TITLE
Vendoring Qt.py

### ISSUE THREAD

**Issue by davidlatwe** [jchanvfx/NodeGraphQt#93]
Hi @jchanvfx , I wonder what do you think about vendoring [mottosso/Qt.py](https://github.com/mottosso/Qt.py) so the NodeGraphQt would be able to support both PySide2 and PyQt5.

I am currently working on this on my fork and having some progress, please let me know what you think. :)

Thanks, and great project !

**Comment by jchanvfx** [comment]
Hey @davidlatwe,

Thanks for checking out the framework 😸 , supporting both `PySide` & `PyQt5` sounds great it's something I plan to do in the future but currently the node graph is still very much a wip and I'm focusing on implementing the basic features at the moment 😃.

Cheers,
Johnny
